### ISSUE TITLE
SSO only config/behavior

### ISSUE THREAD

**Issue by heubeck** [apache/incubator-answer#592] opened 2023-10-28 17:34 UTC
When having AnswerDEV configured with OAuth, it still shows both, "Log In" and "Sign Up".

The login form offers a email/password login, that may be disallowed in a SSO only setup like it is usual in enterprises:
![image](https://github.com/apache/incubator-answer/assets/40993644/dd877cfa-a4d3-45d1-bab5-53f51ee8e345)

Having user registration disallowed in the configuration, the sign up form only offers SSO:
![image](https://github.com/apache/incubator-answer/assets/40993644/ac68fbcb-0f70-4c39-bd5f-955eb6807c18)

And finally, users still can change their password, or disconnect from the SSO provider:
![image](https://github.com/apache/incubator-answer/assets/40993644/81ddb5db-daf5-438f-b85f-72b21c4e33e9)

It would be great, to have an option "SSO only", which only offers the SSO login (no login form, no registration form), and hides the change password and disconnect from SSO provider option on the edit profile pages.

**Comment by mortenbirkelund** [comment] 2023-10-28 19:31
I would like to see an SSO only mode also.

**Comment by fenbox** [comment] 2023-10-29 00:32
Duplicate of #565

**Closed** 2023-12-14 09:30 UTC
Labels: duplicate, enhancement
