### ISSUE TITLE
Support uploading video files

### ISSUE THREAD

**Issue by chenyong0923** [apache/incubator-answer#1155] opened 2024-10-25 06:57 UTC
## Is your enhancement request related to a problem? Please describe

When I post a message, I can upload video files.

## Describe alternatives you've considered

![image](https://github.com/user-attachments/assets/c08c044e-c034-4df3-9a4b-108ffb1a5f26)

**Comment by sy-records** [comment] 2024-10-25 07:16
Duplicate of #211

**Closed by sy-records** 2024-10-25 07:16 UTC
Labels: enhancement
