### ISSUE TITLE
In some cases, reputation of newly registered users does not change to 1 after activation.

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#832] opened 2024-03-08 03:36 UTC
## Describe the bug

Users register by email, but even after activation, their reputation is still 0.

### To Reproduce

1. Register with email until see the page blew:
  ![img_v3_028p_e44701e8-009b-47db-af8a-0340757d664g](https://github.com/apache/incubator-answer/assets/360618/ff14323e-15dc-482f-ae0d-3e7615bfc740)
2. I don't receive the email, click on the "Change Email" button to update and resend the activation email
3. Click the activation link in the final email received to activate account
4. Reputation is still 0

Currently unable to find a 100% reproducible solution, but may encounter it periodically.

**If anyone finds any other way to reproduce it, please let me know, thank you very much.**

### Expected behavior

The reputation will [become 1](https://answer.apache.org/docs/reputation#additional-rules) after activation.

### Screenshots

<img width="870" alt="image" src="https://github.com/apache/incubator-answer/assets/360618/64a01fe2-dcab-48b4-8c08-ad3715a9a98b">

### Platform

- Device: Desktop
- OS: macOS
- Browser and version: Chrome
- Version: v1.2.5

**Comment by ShirleyHhh** [comment] 2024-03-08 10:01
also had this problem

**Comment by surapuramakhil** [comment] 2024-03-10 16:51
This issue is a duplicate of https://github.com/apache/incubator-answer/issues/782

**Comment by fenbox** [comment] 2024-03-11 04:02
Added reproduction steps.

**Comment by hgaol** [comment] 2024-03-12 15:04
Hi @fenbox , I'd like to try to fix this issue, thx!

**Closed** 2024-04-18 08:46 UTC
Labels: bug, duplicate
