### ISSUE TITLE
Date is wrong in search result page

### ISSUE THREAD

**Issue by UlricQin** [apache/incubator-answer#307] opened 2023-04-07 10:21 UTC
<img width="966" alt="image" src="https://user-images.githubusercontent.com/2769466/230592454-cfcc9c0c-8127-416a-a3ea-513ace3057f7.png">

**Comment by kumfo** [comment] 2023-08-24 08:15
what version of the program you are using? I can't reproduce this result.

**Comment by fenbox** [comment] 2023-11-28 03:30
Fixed in v1.2.0

**Closed by fenbox** 2023-11-28 03:30 UTC
Labels: bug
