### ISSUE TITLE
Scrollbar bug & more

### ISSUE THREAD

**Issue by Slluxx** [apache/incubator-answer#429] opened 2023-07-05 03:33 UTC
### Scrollbar bug
Create a new post and quickly move the mouse over the available icons in the wysiwyg editor. If you do it fast enough, multiple popups are open at the same time and one is forced into the next line, which not just looks weird, it can also shift the entire page because of a scrollbar appearing and then disappearing again. I tested this on a 1920x1080 monitor in fullscreen. If the scrollbar exists ahead of time, no noticible shift happens and the miss-placed popup is way harder to notice.

### Visists counter
The counter goes up even if the page is just refreshed. This is not acceptable as it can be used to artificially blow posts up and annoy staff / visitors. There needs to be some kind of check to prevent this. This is not easy as guests should also count but there needs some kind of check in place. Maybe not IP but a few semi-unique combined pieces of information for guests and account ids for logged in users. Doesn't need a  100% waterproof solution but at least it needs to be thought about.

### Multiple different OAuth provider
Probably belongs into answerdev/plugins but i'll note it here anyway.
Having one OAuth provider is not enough. I should be able to use as many as i want to and not be locked to one to increase the potential userbase.

### Answering my own question inside the content, not a new answer.
If i have a simple question that i want to write an answer for, i am forced to put something inside the the "content" textbox. Instead of forcing me to write something super obvious or just repeating the question from the title, i should be allowed to put the answer in directly. One real example:

Title: "What are the reasons for a ban?"
Content: "Is there a list of things that i can avoid to get banned?"
Self-Answer: "Yes, [...]"

The person was forced to basically write the same question inside the content because the title was so self-explanatory that there was nothing of value to add. It doesn't look good, adds nothing of value and could be much more compact and readable if the person was just allowed to put the answer into that content block.

I get that not every question is that obvious and sometimes more context is needed but in hyper specialized communities, self-answered questions usually are that simple and should be accounted for.

**Comment by Slluxx** [comment] 2023-07-05 10:08
@LinkinStars I thought about doing it like that but what if i want/need 2 OAuth Basic provider ([because way more than just google and github exist](https://en.wikipedia.org/wiki/List_of_OAuth_providers))? If it actually is possible to build with multiple `--with github.com/answerdev/plugins/connector/basic` (which i doubt but did not test), it would become quite annoying in the admin pannel to distinguish between them. OAuth simple should have a way to add however many providers a user desires.

Thanks for listening and accepting my feedback!

**Comment by Slluxx** [comment] 2023-07-05 12:34
A few more things i noticed:

### User deletion
Deleting a user does not really delete a user. Some information is still available in the dashboard and thus in the database. I should be able to prune/force delete to remove **everything** from that user. I am not sure what the best way to handle comments/answers on other users questions would be like (eg remove everything and replace with generic message or keep message and replace username with `deleted-user`, `banned-user` or whatever) but keeping certain userdata when specifically deleting a user is a no-go

### Compliances (GDPR/EU/...)
Cookie notices, user information requests/dumps/deletions

### Installations
When setting this up with a database and the database name can not be found, it should asked to create the database instead of throwing an error message.

**Comment by fenbox** [comment] 2023-07-24 08:20
> Answering my own question inside the content, not a new answer.

Thank you for your suggestion. While we understand your point of view, Answer's design is intended to ensure high-quality content and readability. Therefore, we recommend separating questions and answers into different sections. 

If your question and answer are very simple, you can provide the same content in both sections, which will not affect the quality or readability.

**Comment by Slluxx** [comment] 2023-07-26 13:29
> If your question and answer are very simple, you can provide the same content in both sections, which will not affect the quality or readability.

> Answer's design is intended to ensure high-quality content and readability.

I strongly disagree. Text, that doesn't add any value is superfluous and therefore not "high-quality content".


Aside from this, id like to know if my [previous comment](https://github.com/answerdev/answer/issues/429#issuecomment-1621668622) was/is acknowledged in any way

**Comment by shuashuai** [comment] 2023-08-31 07:51
> Create a new post and quickly move the mouse over the available icons in the wysiwyg editor. If you do it fast enough, multiple popups are open at the same time and one is forced into the next line, 

Can you provide a video to reproduce this for fast mouse movement that opens multiple windows? You can go to [our community](https://meta.answer.dev) to submit this video.

**Comment by Slluxx** [comment] 2023-08-31 16:04
No, sorry. Since sqlite cant be reliably used and other issues and limitations that occurred, i moved away from answerdev and cant replicate this anymore without setting it back up. All you need to do is make the window a bit smaller and then move the mouse cursor over the icons in the WYSISYG editor. Hovering over an icon creates a popup, **not a window**, and you can move the mouse faster to another icon than the previous popup is closing, thus pushing one popup into the next line. I am not exactly sure how the window size plays into this but i assume that the scrollbar can appear because 2 popups make the site content larger in height and if content>window, the scrollbar gets enabled - making this whole thing just very ugly to look at.

It was easy to repeat, so just try it a few times.

**Comment by shuashuai** [comment] 2023-09-01 08:25
> No, sorry. Since sqlite cant be reliably used and other issues and limitations that occurred, i moved away from answerdev and cant replicate this anymore without setting it back up. All you need to do is make the window a bit smaller and then move the mouse cursor over the icons in the WYSISYG editor. Hovering over an icon creates a popup, **not a window**, and you can move the mouse faster to another icon than the previous popup is closing, thus pushing one popup into the next line. I am not exactly sure how the window size plays into this but i assume that the scrollbar can appear because 2 popups make the site content larger in height and if content>window, the scrollbar gets enabled - making this whole thing just very ugly to look at.
> 
> It was easy to repeat and also very obvious, so just try it a few times.
> 
> Edit: Nvm i have an account on your community forum so i can just record it there.
> 
>  Untitled.Project.mp4
 
Thanks for the feedback. This bug is caused by bootstrap tooltips. I will use the native title instead of tooltips. And fixed in v1.1.3.

**Closed** 2023-12-25 03:36 UTC
Labels: bug
